- name: Check if service is running on worker nodes
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
  register: k3s_running

- name: Join worker nodes
  when: k3s_running.state != "started"
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 sh -s - agent \
      --server https://{{ virtual_ip }}:6443
