ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_SSH_PASS') }}"
ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
virtual_ip: 192.168.1.60