- name: Uninstall k3s on servers
  when: "'master1' or 'masterx' in group_names"
  ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh

- name: Uninstall k3s on workers
  when: "'worker' in group_names"
  ansible.builtin.shell: /usr/local/bin/k3s-agent-uninstall.sh

- name: Disable haproxy & keepalived
  when: "'haproxy' in group_names"
  ansible.builtin.shell: |
    systemctl stop haproxy keepalived |
    systemctl disable haproxy keepalived |
    rm -f /etc/systemd/system/haproxy.service /etc/systemd/system/keepalived.service |
    systemctl daemon-reload |
    rm -f /etc/haproxy/haproxy.cfg /etc/keepalived/keepalived.conf