- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Disable Swap
  when: "'master', 'worker' in group_names"
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Ensure Swap is disabled
  when: "'master', 'worker' in group_names"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: '#&'
    backup: false
