- name: Check if k3s is already installed
  ansible.builtin.shell: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Download k3s installation script
  when: k3s_installed.rc != 0
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Install k3s on the first master
  when: k3s_installed.rc != 0
  ansible.builtin.shell: |
    K3S_TOKEN=secrettoken1337 sh /tmp/k3s_install.sh -s - server \
      K3S_KUBECONFIG_MODE="644" \
      --cluster-init \
      --tls-san={{ hostvars['virtual_ip']['virtual_ip'] }}
