- name: Check if k3s is already installed
  ansible.builtin.shell: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Install k3s on subsequent masters and join cluster
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 sh /tmp/k3s_install.sh -s - server \
      K3S_KUBECONFIG_MODE="644" \
      --tls-san={{ hostvars['virtual_ip']['virtual_ip'] }}
