- name: Check if k3s is already installed
  ansible.bultin.shell: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Install k3s on subsequent masters and join cluster
  when: k3s_installed.rc != 0
  ansible.bultin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 sh -s - server \
      --server https://{{ hostvars['master1']['ansible_host'] }}:6443 \
      --tls-san={{ [hostvars['virtual_ip']['virtual_ip']] }} 
