- name: Check if k3s is already installed
  ansible.builtin.shell: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Install k3s on subsequent masters and join cluster
  when: k3s_installed.failed
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 sh -s - server \
      --server https://{{ hostvars['master1']['ansible_host'] }}:6443 \
      K3S_KUBECONFIG_MODE="644" \
      --tls-san={{ virtual_ip }}
