- name: Check if namespace exists
  ansible.builtin.shell: kubectl get namespace kube-system --ignore-not-found
  register: namespace_exists
  when: "'master1' in group_names"

- name: Copy manifest to /tmp
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/ha-k3s/manifests/metrics-server.yaml"
    dest: /tmp/metrics-server.yaml
  when: namespace_exists.stdout | length == 0 and "'master1' in group_names"

- name: Apply metrics-server.yaml manifest
  ansible.builtin.shell: kubectl apply -f /tmp/metrics-server.yaml
  when: namespace_exists.stdout == "" and "'master1' in group_names"

- name: Check if metrics-server pod is running
  ansible.builtin.shell: kubectl get pods -n kube-system -l k8s-app=metrics-server --ignore-not-found
  register: metrics_server_pod
  when: "'master1' in group_names"
