- name: Install loadbalancer
  hosts: loadbalancer
  become: yes
  roles:
  - common
  - loadbalancer

- name: Install k3s on masters
  hosts: master1:masterx
  become: yes
  roles:
  - common
  - k3s_master

- name: Install k3s on workers
  hosts: worker
  become: yes
  roles:
  - common
  - k3s_worker

- name: Cleanup
  hosts: all
  become: yes
  roles:
  - cleanup