all:
  children:
    m1:
      hosts:
        m1:
          ansible_host: 192.168.1.50
    masterx:
      hosts:
        master2:
          ansible_host: 192.168.1.51
        master3:
          ansible_host: 192.168.1.52
    worker:
      hosts:
        worker1:
          ansible_host: 192.168.1.53
        worker2:
          ansible_host: 192.168.1.54
        worker3:
          ansible_host: 192.168.1.55
    loadbalancer:
      hosts:
        lb1:
          ansible_host: 192.168.1.56
        lb2:
          ansible_host: 192.168.1.57
