galaxy_info:
  author: alex
  description: provisions a one master and x worker nodes k3s cluster, with argoCD installed using helm

  issue_tracker_url: http://example.com/issue/tracker

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
   - name: ubuntu
  versions:
    - all