- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Copy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ loadbalancer_haproxy_conf_path }}"
  notify: Restart HAProxy

- name: Copy Keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ loadbalancer_keepalived_conf_path }}"
  notify: Restart Keepalived

- name: Start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Start Keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: yes
