- name: Install HAProxy and Keepalived
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy
    - keepalived

- name: Copy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ loadbalancer_haproxy_conf_path }}"
  notify: Restart HAProxy and Keepalived

- name: Copy Keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ loadbalancer_keepalived_conf_path }}"
  notify: Restart HAProxy and Keepalived

- name: Start HAProxy and Keepalived
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - haproxy
    - keepalived
