- name: Disable haproxy & keepalived
  ansible.builtin.shell: |
    systemctl stop haproxy keepalived |
    systemctl disable haproxy keepalived |
    rm -f {{ haproxy_service_path }} {{ keepalived_service_path }} |
    systemctl daemon-reload |
    rm -f {{ haproxy_conf_path }} {{ keepalived_conf_path }}

- name: Uninstall haproxy & keepalived
  ansible.builtin.apt:
    name: haproxy, keepalived
    state: absent
