- name: Include first master tasks
  ansible.builtin.include_tasks: master1.yml
  when: "'m1' in group_names"

- name: Include subsequent master tasks
  ansible.builtin.include_tasks: masterx.yml
  when: "'masterx' in group_names"
