- name: Check if k3s is already installed
  ansible.builtin.command: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Install k3s on the first master
  when: k3s_installed.failed
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 \
    K3S_KUBECONFIG_MODE="644" \
    sh -s - server \
    --cluster-init \
    --tls-san={{ virtual_ip }}


