- name: Check if k3s is already installed
  ansible.builtin.systemd:
    name: k3s
    state: started
  register: k3s_installed

- name: Install k3s on subsequent masters and join cluster
  when: k3s_installed.state != "started"
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN=secrettoken1337 \
    K3S_KUBECONFIG_MODE="644" \
    sh -s - server \
    --server https://{{ hostvars['master1']['ansible_host'] }}:6443 \
    K3S_KUBECONFIG_MODE="644" \
    --tls-san={{ virtual_ip }}
