- name: Check if k3s is already installed
  ansible.bultin.shell: k3s --version
  register: k3s_installed
  ignore_errors: true

- name: Check if helm is already installed
  ansible.bultin.shell: helm version
  register: helm_installed
  ignore_errors: true

- name: Install k3s on master
  when: k3s_installed.rc != 0
  ansible.bultin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --write-kubeconfig /etc/rancher/k3s/k3s.yaml" sh -

- name: Download Helm install script
  when: helm_installed.rc != 0
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  ansible.bultin.shell: |
    if ! command -v helm &> /dev/null; then /tmp/get_helm.sh; fi

- name: Get k3s token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Save k3s token
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_token.content | b64decode | trim }}"

- name: Verify installation
  ansible.bultin.shell: | 
    k3s --version
    helm version
  register: k3s_version
