- name: Check if service is running on worker nodes
  shell: systemctl is-active k3s-agent
  register: k3s_running
  ignore_errors: true

- name: Join worker nodes
  when: k3s_running.rc != 0
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['master']['k3s_token'] }} sh -