name: Lint code on push and test locally 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature-*

jobs:
  linter:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ansible lint
        uses: ansible/ansible-lint@main
        with:
          args: -c .ansible-lint

  test-locally:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: playbook.yml
          inventory: ${{ secrets.ANSIBLE_INVENTORY }}
          configuration: |
            [defaults]
            host_key_checking = False
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_SSH_PASS: ${{ secrets.ANSIBLE_SSH_PASS }}
          ANSIBLE_BECOME_PASSWORD: ${{ secrets.ANSIBLE_BECOME_PASSWORD }}
        options: --check
